addSbtPlugin("com.eed3si9n"      % "sbt-assembly" % "1.2.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.13")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "2.1.1")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"  % "0.6.3")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.13")
